name: Build Custom EasyEngine

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Phar
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Clean environment
        run: |
          rm -f composer.lock
          rm -rf vendor

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
          extensions: pcntl, curl, sqlite3, zip, dom, mbstring, json, phar

      - name: Setup Composer
        run: |
          composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer config platform.php 7.3
          composer config discard-changes true

      - name: Install dependencies
        run: |
          composer require "easyengine/site-command:dev-develop" --no-update
          composer install --prefer-dist --no-dev --no-progress --no-interaction --optimize-autoloader

      - name: Fix potential path issues
        run: |
          find vendor -type f -name "*.php" -exec sed -i 's/__DIR__/dirname(__DIR__)/g' {} +

      - name: Build Phar with proper includes
        run: |
          php -dphar.readonly=0 utils/make-phar.php easyengine.phar --no-compression
          chmod +x easyengine.phar

      - name: Validate Phar
        run: |
          php easyengine.phar cli info