name: Build Custom EasyEngine

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Phar
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
          extensions: pcntl, curl, sqlite3, zip, dom, mbstring, json

      - name: Setup Composer
        run: |
          composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction
          composer update easyengine/site-command easyengine/easyengine --with-all-dependencies

      - name: Set custom version
        run: |
          echo "4.0.0-custom-$(date +%Y%m%d)-$(git rev-parse --short HEAD)" > VERSION

      - name: Build Phar
        run: php -dphar.readonly=0 utils/make-phar.php easyengine.phar

      - name: Test Phar
        run: php easyengine.phar --info

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: easyengine-custom.phar
          path: easyengine.phar
          retention-days: 5