name: Build Custom EasyEngine

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Phar
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Clean environment
        run: |
          rm -rf vendor composer.lock

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
          extensions: pcntl, curl, sqlite3, zip, dom, mbstring, json, phar

      - name: Setup Composer authentication
        run: |
          composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer config --global --auth github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer config -g repo.packagist composer https://packagist.org

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-dev --no-progress --no-interaction --optimize-autoloader
          composer dump-autoload --optimize --classmap-authoritative

      - name: Prepare for PHAR build
        run: |
          # Copy required files to temporary directory
          mkdir -p phar-build
          cp -r php bin utils VERSION vendor phar-build/

      - name: Build PHAR
        run: |
          cd phar-build
          php -dphar.readonly=0 ../utils/make-phar.php easyengine.phar
          chmod +x easyengine.phar
          mv easyengine.phar ../
          cd ..

      - name: Test PHAR
        run: |
          php easyengine.phar cli info

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: easyengine-custom.phar
          path: easyengine.phar
          retention-days: 5